# Generated by Django 5.2.15 on 2026-09-12 08:48

import django.db.models.deletion
import utils.encryption
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("GOOGLE", "Google"), ("APPLE", "Apple")],
                        max_length=32,
                    ),
                ),
                ("subject_hash", models.CharField(max_length=64)),
                ("subject", utils.encryption.EncryptedTextField()),
                ("email", utils.encryption.EncryptedEmailField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signacore_social_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "subject_hash"),
                        name="unique_signacore_social_identity",
                    )
                ],
            },
        ),
    ]
