# Generated by Django 5.2.15 on 2026-09-12 08:55

import hashlib
import hmac

from django.conf import settings
from django.db import migrations, models


def backfill_email_hashes(apps, schema_editor):
    account_profile = apps.get_model("accounts", "AccountProfile")
    for profile in account_profile.objects.all().iterator():
        email = (profile.email or "").strip().casefold()
        profile.email_hash = hmac.new(
            settings.SECRET_KEY.encode(),
            email.encode(),
            hashlib.sha256,
        ).hexdigest() if email else ""
        profile.save(update_fields=["email_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_socialidentity"),
        ("documents", "0005_backfill_legacy_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="email_hash",
            field=models.CharField(
                db_index=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.RunPython(backfill_email_hashes, migrations.RunPython.noop),
    ]
