# Generated by Django 5.2.15 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_accountprofile_email_hash"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accountprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email_hash", ""), _negated=True),
                fields=("email_hash",),
                name="unique_signacore_account_email_hash",
            ),
        ),
    ]
