# Generated by Django 5.2.15 on 2026-10-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_expand_pricing_plan_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsubscription",
            name="stripe_subscription_item_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organizationsubscription",
            name="stripe_subscription_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
