# Generated by Django 5.2.15 on 2026-06-26 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("original_pdf", models.FileField(upload_to="signacore/originals/")),
                (
                    "signed_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="signacore/signed/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("PARTIALLY_SIGNED", "Partially Signed"),
                            ("COMPLETED", "Completed"),
                            ("VOIDED", "Voided"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("voided_reason", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signacore_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("SIGNATURE", "Signature"),
                            ("INITIALS", "Initials"),
                            ("TEXT", "Text"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("page", models.PositiveIntegerField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("is_required", models.BooleanField(default=True)),
                (
                    "detection_source",
                    models.CharField(
                        choices=[
                            ("ACROFORM", "AcroForm"),
                            ("HEURISTIC", "Heuristic"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ("page", "order"),
            },
        ),
    ]
