# Generated by Django 5.2.15 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("SIGNATURE", "Signature"),
                    ("INITIALS", "Initials"),
                    ("TEXT", "Text"),
                    ("CHECKBOX", "Checkbox"),
                ],
                max_length=32,
            ),
        ),
    ]
