# Generated by Django 5.2.15 on 2026-09-05 14:01

import django.db.models.deletion
import utils.encryption
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documentfield_checkbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_email",
                    utils.encryption.EncryptedEmailField(blank=True, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("DOCUMENT_LIST", "Document List"),
                            ("DOCUMENT_VIEW", "Document View"),
                            ("DOCUMENT_UPLOAD", "Document Upload"),
                            ("DOCUMENT_UPDATE", "Document Update"),
                            ("DOCUMENT_VOID", "Document Void"),
                            ("DOCUMENT_DOWNLOAD", "Document Download"),
                            ("FIELD_CREATE", "Field Create"),
                            ("FIELD_UPDATE", "Field Update"),
                            ("FIELD_DELETE", "Field Delete"),
                            ("SIGNING_REQUEST_SEND", "Signing Request Send"),
                            ("SIGNING_REQUEST_RESEND", "Signing Request Resend"),
                            ("ADMIN_USER_LIST", "Admin User List"),
                            ("ADMIN_USER_CREATE", "Admin User Create"),
                            ("ADMIN_PASSWORD_CHANGE", "Admin Password Change"),
                            ("AUDIT_LOG_LIST", "Audit Log List"),
                        ],
                        max_length=64,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=128)),
                ("summary", models.CharField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ip_address",
                    utils.encryption.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "user_agent",
                    utils.encryption.EncryptedTextField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signacore_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
