# Generated by Django 5.2.15 on 2026-09-12 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("documents", "0005_backfill_legacy_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="accounts.organization",
            ),
        ),
    ]
