# Generated by Django 5.2.15 on 2026-09-13 09:21

from pathlib import Path

from django.conf import settings
from django.db import migrations, models

import utils.file_storage


def encrypt_existing_document_files(apps, schema_editor):
    document_model = apps.get_model("documents", "Document")
    media_root = Path(settings.MEDIA_ROOT)
    for original_name, signed_name in document_model.objects.values_list("original_pdf", "signed_pdf").iterator():
        for file_name in (original_name, signed_name):
            if file_name:
                utils.file_storage.encrypt_path_in_place(media_root / file_name)


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_alter_adminauditlog_action"),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_document_files, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="original_pdf",
            field=models.FileField(
                storage=utils.file_storage.EncryptedFileSystemStorage(),
                upload_to=utils.file_storage.original_pdf_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="signed_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=utils.file_storage.EncryptedFileSystemStorage(),
                upload_to=utils.file_storage.signed_pdf_upload_to,
            ),
        ),
    ]
