# Generated by Django 5.2.15 on 2026-09-13 09:26

import utils.encryption
from django.db import migrations


def encrypt_existing_document_metadata(apps, schema_editor):
    document_model = apps.get_model("documents", "Document")
    field_model = apps.get_model("documents", "DocumentField")
    audit_model = apps.get_model("documents", "AdminAuditLog")

    for document in document_model.objects.all().iterator():
        document_model.objects.filter(pk=document.pk).update(
            title=document.title,
            voided_reason=document.voided_reason,
        )
    for document_field in field_model.objects.all().iterator():
        field_model.objects.filter(pk=document_field.pk).update(label=document_field.label)
    for audit_log in audit_model.objects.all().iterator():
        metadata = dict(audit_log.metadata or {})
        if "reason" in metadata:
            metadata["reason_provided"] = bool(metadata.pop("reason"))
        audit_model.objects.filter(pk=audit_log.pk).update(
            summary=audit_log.summary,
            metadata=metadata,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_alter_document_original_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminauditlog",
            name="summary",
            field=utils.encryption.EncryptedTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=utils.encryption.EncryptedTextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="document",
            name="voided_reason",
            field=utils.encryption.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="label",
            field=utils.encryption.EncryptedTextField(max_length=255),
        ),
        migrations.RunPython(encrypt_existing_document_metadata, migrations.RunPython.noop),
    ]
