# Generated by Django 5.2.15 on 2026-09-18 07:19

import utils.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_alter_adminauditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="authored_content",
            field=utils.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="source",
            field=models.CharField(
                choices=[("UPLOADED", "Uploaded PDF"), ("AUTHORED", "Created in SignaCore")],
                default="UPLOADED",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("DOCUMENT_LIST", "Document List"),
                    ("DOCUMENT_VIEW", "Document View"),
                    ("DOCUMENT_UPLOAD", "Document Upload"),
                    ("DOCUMENT_AUTHOR", "Document Author"),
                    ("DOCUMENT_UPDATE", "Document Update"),
                    ("DOCUMENT_VOID", "Document Void"),
                    ("DOCUMENT_DOWNLOAD", "Document Download"),
                    ("FIELD_CREATE", "Field Create"),
                    ("FIELD_UPDATE", "Field Update"),
                    ("FIELD_DELETE", "Field Delete"),
                    ("SIGNING_REQUEST_SEND", "Signing Request Send"),
                    ("SIGNING_REQUEST_RESEND", "Signing Request Resend"),
                    ("ADMIN_USER_LIST", "Admin User List"),
                    ("ADMIN_USER_CREATE", "Admin User Create"),
                    ("ORGANIZATION_MEMBER_LIST", "Organization Member List"),
                    ("ORGANIZATION_MEMBER_INVITE", "Organization Member Invite"),
                    ("ORGANIZATION_MEMBER_REMOVE", "Organization Member Remove"),
                    ("ADMIN_PASSWORD_CHANGE", "Admin Password Change"),
                    ("AUDIT_LOG_LIST", "Audit Log List"),
                    ("BILLING_VIEW", "Billing View"),
                    ("BILLING_CHECKOUT", "Billing Checkout"),
                    ("BILLING_PORTAL", "Billing Portal"),
                    ("OAUTH_LOGIN", "OAuth Login"),
                    ("EMAIL_REGISTER", "Email Registration"),
                    ("EMAIL_LOGIN", "Email Login"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="detection_source",
            field=models.CharField(
                choices=[
                    ("ACROFORM", "AcroForm"),
                    ("HEURISTIC", "Heuristic"),
                    ("MANUAL", "Manual"),
                    ("AUTHORED", "Authored document"),
                ],
                max_length=32,
            ),
        ),
    ]
