# Generated by Django 5.2.15 on 2026-09-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0015_alter_adminauditlog_action_document_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="import_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("SIGNATURE", "Signature"),
                    ("INITIALS", "Initials"),
                    ("TEXT", "Text"),
                    ("MULTILINE", "Multiline text"),
                    ("CHECKBOX", "Checkbox"),
                ],
                max_length=32,
            ),
        ),
    ]
