# Generated by Django 5.2.15 on 2026-09-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0017_convert_legacy_acroform_field_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfield",
            name="is_comb",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documentfield",
            name="max_length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="detection_source",
            field=models.CharField(
                choices=[
                    ("ACROFORM", "AcroForm"),
                    ("ANCHOR", "Anchor tag"),
                    ("HEURISTIC", "Heuristic"),
                    ("MANUAL", "Manual"),
                    ("AUTHORED", "Authored document"),
                ],
                max_length=32,
            ),
        ),
    ]
