# Generated by Django 5.2.15 on 2026-09-27 20:34

import utils.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0019_convert_authored_field_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfield",
            name="group_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="documentfield",
            name="option_value",
            field=utils.encryption.EncryptedTextField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="documentfield",
            name="options",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("SIGNATURE", "Signature"),
                    ("INITIALS", "Initials"),
                    ("TEXT", "Text"),
                    ("MULTILINE", "Multiline text"),
                    ("CHECKBOX", "Checkbox"),
                    ("DROPDOWN", "Dropdown"),
                    ("RADIO", "Radio option"),
                ],
                max_length=32,
            ),
        ),
    ]
