# Generated by Django 5.2.15 on 2026-10-07 01:14

import utils.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0020_documentfield_group_key_documentfield_option_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="send_message",
            field=utils.encryption.EncryptedTextField(blank=True, default=""),
        ),
    ]
