# Generated by Django 5.2.15 on 2026-10-10 12:16

import django.db.models.deletion
import utils.encryption
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0021_document_send_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfield",
            name="prefilled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentfield",
            name="prefilled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signacore_prefilled_fields",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentfield",
            name="prefilled_value",
            field=utils.encryption.EncryptedTextField(blank=True, null=True),
        ),
    ]
