# Generated by Django 5.2.15 on 2026-10-10 14:00

import django.db.models.deletion
import utils.encryption
import utils.file_storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0021_document_send_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfield",
            name="assigned_to",
            field=models.CharField(
                choices=[("SENDER", "The sender"), ("SIGNER", "The signer")], default="SIGNER", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="documentfield",
            name="sender_filled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentfield",
            name="sender_filled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signacore_sender_filled_fields",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentfield",
            name="sender_filled_ip",
            field=utils.encryption.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentfield",
            name="sender_signature",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=utils.file_storage.EncryptedFileSystemStorage(),
                upload_to=utils.file_storage.sender_signature_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="documentfield",
            name="sender_value",
            field=utils.encryption.EncryptedTextField(blank=True, null=True),
        ),
    ]
