# Generated by Django 5.2.15 on 2026-10-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0022_fields_belong_to_someone"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="original_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
