# Generated by Django 5.2.15 on 2026-06-26 20:07

import django.db.models.deletion
import utils.encryption
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigningRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("signer_email", utils.encryption.EncryptedEmailField()),
                (
                    "signer_name",
                    utils.encryption.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OTP_VERIFIED", "OTP Verified"),
                            ("SIGNED", "Signed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("otp_hash", models.CharField(blank=True, max_length=128, null=True)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ip_address",
                    utils.encryption.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "user_agent",
                    utils.encryption.EncryptedTextField(blank=True, null=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signing_requests",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="FieldSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("SIGNATURE_PNG", "Signature PNG"),
                            ("INITIALS_PNG", "Initials PNG"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "text_value",
                    utils.encryption.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "image_value",
                    models.FileField(
                        blank=True, null=True, upload_to="signacore/sigs/"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="documents.documentfield",
                    ),
                ),
                (
                    "signing_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="signing.signingrequest",
                    ),
                ),
            ],
        ),
    ]
