# Generated by Django 5.2.15 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldsubmission",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("SIGNATURE_PNG", "Signature PNG"),
                    ("INITIALS_PNG", "Initials PNG"),
                    ("CHECKBOX", "Checkbox"),
                ],
                max_length=32,
            ),
        ),
    ]
