# Generated by Django 5.2.15 on 2026-09-12 08:54

import hashlib
import hmac

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_signer_email_hashes(apps, schema_editor):
    signing_request = apps.get_model("signing", "SigningRequest")
    for request in signing_request.objects.all().iterator():
        email = request.signer_email.strip().casefold()
        request.signer_email_hash = hmac.new(
            settings.SECRET_KEY.encode(),
            email.encode(),
            hashlib.sha256,
        ).hexdigest()
        request.save(update_fields=["signer_email_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ("signing", "0002_fieldsubmission_checkbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="signingrequest",
            name="signer_email_hash",
            field=models.CharField(
                db_index=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="signingrequest",
            name="signer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signacore_signing_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_signer_email_hashes, migrations.RunPython.noop),
    ]
