# Generated by Django 5.2.15 on 2026-09-13 09:21

from pathlib import Path

from django.conf import settings
from django.db import migrations, models

import utils.file_storage


def encrypt_existing_signature_images(apps, schema_editor):
    submission_model = apps.get_model("signing", "FieldSubmission")
    media_root = Path(settings.MEDIA_ROOT)
    for (image_name,) in submission_model.objects.exclude(image_value="").values_list("image_value").iterator():
        if image_name:
            utils.file_storage.encrypt_path_in_place(media_root / image_name)


class Migration(migrations.Migration):

    dependencies = [
        ("signing", "0003_signingrequest_signer_email_hash_and_more"),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_signature_images, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="fieldsubmission",
            name="image_value",
            field=models.FileField(
                blank=True,
                null=True,
                storage=utils.file_storage.EncryptedFileSystemStorage(),
                upload_to=utils.file_storage.signature_image_upload_to,
            ),
        ),
    ]
