# Generated by Codex on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signing", "0004_alter_fieldsubmission_image_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="signingrequest",
            name="otp_last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
