# Generated by Django 5.2.15 on 2026-10-05 23:04

import utils.file_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signing", "0005_signingrequest_otp_last_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="signingrequest",
            name="signed_pdf",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=utils.file_storage.EncryptedFileSystemStorage(),
                upload_to=utils.file_storage.signer_copy_upload_to,
            ),
        ),
    ]
