# Generated by Django 5.2.15 on 2026-10-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signing", "0006_signingrequest_signed_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="signingrequest",
            name="otp_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
