# Generated by Django 5.2.15 on 2026-10-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signing", "0007_signingrequest_otp_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="signingrequest",
            name="follow_up_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
