# Generated by Django 5.2.15 on 2026-10-10 11:51

import django.db.models.deletion
import django.utils.timezone
import utils.encryption
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signing", "0008_signingrequest_follow_up_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigningEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("SENT", "Signing request sent"),
                            ("OPENED", "Document opened"),
                            ("CODE_SENT", "Verification code sent"),
                            ("CODE_VERIFIED", "Email verified"),
                            ("SIGNED", "Signed and submitted"),
                            ("REOPENED", "Reopened for correction"),
                            ("COPY_DELIVERED", "Completed copy emailed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", utils.encryption.EncryptedTextField(blank=True, null=True)),
                ("user_agent", utils.encryption.EncryptedTextField(blank=True, null=True)),
                ("detail", utils.encryption.EncryptedTextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signing_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="signing.signingrequest"
                    ),
                ),
            ],
            options={
                "ordering": ("at", "created_at"),
                "indexes": [models.Index(fields=["signing_request", "at"], name="signing_sig_signing_2471b5_idx")],
            },
        ),
    ]
