# Generated by Django 5.2.15 on 2026-10-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signing", "0010_backfill_the_existing_trail"),
    ]

    operations = [
        migrations.AddField(
            model_name="signingrequest",
            name="signed_pdf_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
