# Generated by Django 5.2.15 on 2026-10-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailSuppression",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("UNSUBSCRIBED", "Unsubscribed"),
                            ("BOUNCED", "Bounced"),
                            ("COMPLAINED", "Marked as spam"),
                        ],
                        default="UNSUBSCRIBED",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
